config/routes.rb
Pinteresting::Application.routes.draw do
  resources :pins do
  resources :comments, :only => [:create]
  member do
    post 'upvote'
    post 'sharevote'
  end
end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "pins#index"
  get "about" => "pages#about" # creates about_path
  

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
    has_many :votes, dependent: :destroy
    has_many :comments
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    validates_attachment_size :image, :in => 0.kilobytes..900.kilobytes

    validates :description, presence: true
    validates :image, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :pins
  has_many :votes, dependent: :destroy

  validates :name, presence: true
  validates_uniqueness_of :name


  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :pin
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 
 	protect_from_forgery with: :exception
 	
 	before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

 	def configure_permitted_parameters
   		devise_parameter_sanitizer.for(:sign_up) << :name
   		devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@pin = Pin.find(params[:pin_id])

		@comment = @pin.comments.create!(comment_params)

		if @comment.errors.any?
			render "posts/show"
		else
			redirect_to @pin
		end
	end


	private


	def comment_params
		@comment_params ||= params.require(:comment).permit(:body).merge(:user_id => current_user.id)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end


def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show] 

 def index
   require 'will_paginate/array'
   @pins = Pin.includes(:votes).group("votes.pin_id").order("count(votes.pin_id) desc").paginate(:page => params[:page], :per_page => 25)
 end


  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end


  def create
    @pin = current_user.pins.build(pin_params)

      if @pin.save
        @pin.votes.create({:user_id => current_user.id, :votetype => "vote" })
        redirect_to @pin, notice: 'Pin was successfully created.'
      else
        render action: 'new'
      end
  end


  def update
      if @pin.update(pin_params)
        redirect_to @pin, notice: 'Pin was successfully updated.'
      else
        render action: 'edit'
      end
  end


  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  def upvote
    @pin = Pin.find(params[:id])
    @vote = Vote.where(:user_id => current_user.id, :pin_id => @pin.id, :votetype => "vote").first
    @pin.votes.create({:user_id => current_user.id, :votetype => "vote" }) unless @vote
    render :nothing => true
  end

  def sharevote
    @pin = Pin.find(params[:id])
    @vote = Vote.where(:user_id => current_user.id, :pin_id => @pin.id, :votetype => "share").first
    @pin.votes.create({:user_id => current_user.id, :votetype => "share" }) unless @vote
    render :nothing => true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <p>
    <strong>
      Posted <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.name %>
    </strong>
    <br/>
    <%= comment.body %>
  </p>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Pinteresting", root_path , class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
   
  <div class="nav navbar-nav navbar-left">
    <% if user_signed_in? %>
      <p class="hello">Hello <%= link_to current_user.name, edit_user_registration_path %></p>
    <% end %>
  </div>  


    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <% if user_signed_in? %>
        <li>
          <%= link_to new_pin_path do %>
            <span class="glyphicon glyphicon-plus"></span> New Pin
          <% end %>
        </li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <div id="fb-root"></div>
</head>
<body>

<%=render "layouts/header" %>

	<div class="container">
		<% flash.each do |name, msg| %>
     <%= content_tag(:div, msg, class: "alert alert-info") %>
     		<% end %>
		<%= yield %>
	</div>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">


<h1>Welcome to my app!</h1>



<p>
  <%= link_to "Log in",new_user_session_path , class: "btn btn-default btn-lg" %>
  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) , class: "btn btn-default btn-lg" %>
  <%= link_to "Sign up", new_user_registration_path , class: "btn btn-primary btn-lg" %>
  
</p>


</div>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>We are working on our one month rails pinteresting app!</h1>

app/views/pages/home.html.erb
<div class="jumbotron center">


<h1>Welcome to my app!</h1>

<% if user_signed_in? %>
	
	Welcome to the User's area!

<% else %>

<p>
	<%= link_to "Log in",new_user_session_path , class: "btn btn-default btn-lg" %>
	<%= link_to "Sign up", new_user_registration_path , class: "btn btn-primary btn-lg" %>
</p>

<% end %>

</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
  <%=render "pages/home" unless user_signed_in?%>


  <div id="pins" class="transitions-enabled">
    <% @pins.each do |pin| %>
  <div class="box panel panel-default">
        <%= link_to image_tag(pin.image.url(:medium)), pin %>
        <div class="panel-body" data-pin="<%= pin.id %>">
        <p><%= pin.description %><br/></p>
        <p><strong><%= pin.user.name if pin.user %></strong></p>
            <p class="vote-text" data-vote="<%= pin.votes.count %>" > <span class="votenum"><%= pin.votes.count %></span> Votes</p>
            <% if user_signed_in? %>
            <span class="vote-block">
            <%= link_to raw("<i class=\"fa fa-thumbs-o-up\"></i> Vote"), upvote_pin_path(pin), method: :post, :remote => true, :class => "vote-btn" %>
            <%= link_to raw("<i class=\"fa fa-facebook-square\"></i> Share"), "#" , :class => "fb-share" %>
            </span>
            <% end %>
        <% if pin.user == current_user %>
            <div class="actions">
              <%= link_to edit_pin_path(pin) do %>
                <span class="glyphicon glyphicon-edit"></span>
                Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
            Delete
            <% end %>
          </div>
          <% end %>

          </div>
        </div>
    <% end %>
</div>

<div class="center">
   <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
    <div class="panel-body" data-pin="<%= @pin.id %>">
      <p><%= @pin.description %></p>
      <p><strong><%= @pin.user.name if @pin.user %></strong></p>
      <% if @pin.user == current_user %>
        <%= link_to edit_pin_path(@pin) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
        <% end %>
      <% end %>
      <p class="vote-text" data-vote="<%= @pin.votes.count %>" ><span class="votenum"><%= @pin.votes.count %></span> Votes</p>
        <% if user_signed_in? %>
          <span class="vote-block">
            <%= link_to raw("<i class=\"fa fa-thumbs-o-up\"></i> Vote"), upvote_pin_path(@pin), method: :post, :remote => true, :class => "vote-btn" %>
            <%= link_to raw("<i class=\"fa fa-facebook-square\"></i> Share"), "#" , :class => "fb-share" %>
          </span>
        <% end %>
      <h2>Comments</h2>
        <div id="comments">
          <%= render :partial => @pin.comments %>
        </div>
        <% if user_signed_in? %>
          <%= form_for [@pin, Comment.new] do |f| %>
            <p>
              <%= f.label :body, "New comment" %></br>
              <%= f.text_area :body %>
            </p>
            <p><%= f.submit "Add Comment" %><p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>